spring:
  datasource:
    url: jdbc:mysql://rm-wz99x2841ssaqvj003o.mysql.rds.aliyuncs.com:3306/example
    username: root
    password: He290802
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jooq:
    sql-dialect: MySQL
  thymeleaf:
    cache: false
  jackson:
    default-property-inclusion: non_null

debug: false
